### PR TITLE
Update Finder.php

### LINKED ISSUE #7: Impossible to save component's configuration on Windows
**Expected behavior:**
Normal use in Windows system
**Actual behavior:**
If you try to update some component's configuration from Theme -> Orange you have an error like this 

`The specified file name [account\account.php] is invalid." on line 471 of C:\xampp\htdocs\tasty\vendor\tastyigniter\flame\src\Pagic\Finder.php#0 C:\xampp\htdocs\tasty\vendor\tastyigniter\flame\src\Pagic\Finder.php(350): Igniter\Flame\Pagic\Finder->validateFileName() #1 C:\xampp\htdocs\tasty\vendor\tastyigniter\flame\src\Pagic\Model.php(565): ...`

**Reproduce steps:**
Install version 3.0 on windows. Change some configuration of your theme, and try to save it.
**Version:**
v3.0.4-beta.20.1

### PR DESCRIPTION
**Pull request by cesarelasorella**
Fixes #7

### CODE REVIEW

**Comment by sampoyigi** [comment]
Might be related to tastyigniter/TastyIgniter#298, will investigate more to see how the changes affects other parts of the code. I'll keep you updated :)

**Comment by cesarelasorella** [comment]
They are different. I already check it. ;)

Il giorno mar 12 mag 2020 alle ore 19:37 Sam Poyigi <
notifications@github.com> ha scritto:

**Comment by sampoyigi** [comment]
Ok. I still somehow feel there's a better approach 🤷‍♂️ I'll keep you updated.

**Comment by sampoyigi** [comment]
Merged! Can you check and let me know if the solution suggested here (tastyigniter/TastyIgniter#298) are still required?

**Pull request merged**
