### PR TITLE
wip on cart item condition

### PR DESCRIPTION
**Pull request by sampoyigi**
@ryanmitchell have a look at this, let me know what you think.

### CODE REVIEW

**Comment by ryanmitchell** [comment]
Is there a change missing from CartConditionManager in the cart extension?
Ref:  ``` traceLog('Deprecated. Use CartConditionManager::instance()->loadCartConditions($cart) instead');```

**Comment by sampoyigi** [comment]
Ah, forgot to push the commit yesterday then panicked this morning lol, anyways I pushed it here https://github.com/tastyigniter/ti-ext-cart/commit/58b9cc8885a88414a21b7993fb9c00b25ad069b6

**Comment by sampoyigi** [comment]
> Then for adding limitations is it as simple as working out which items are applicable in getApplicableItems() on the condition?

Yep, simplez!

**Comment by ryanmitchell** [comment]
Thanks - but not working for me using the coupons extension. It just adds the coupon without calling the getApplicableItems() method.

I’ve added where I’ve got to here:
https://github.com/tastyigniter/ti-ext-coupons/tree/add-limitations

**Comment by sampoyigi** [comment]
Sorry, I forgot to mention its still a work in progress. With the getApplicableItems implemented on the coupon side, I'll have a look at it tonight.

**Comment by sampoyigi** [comment]
Here's the required changes on the themes side for displaying the discounted cart item price

```
<span class="price pull-right">
                        <?php if ($cartItem->hasConditions()) { ?>
                            <s class="text-muted"><?= currency_format($cartItem->subtotalWithoutConditions()); ?></s>/
                        <?php } ?>
                        <?= currency_format($cartItem->subtotal); ?>
                    </span>
```

**Comment by ryanmitchell** [comment]
Finally got some time to look at this - it looks great and opens the possibility of buy one get one free type of discounts. You've taken it way further than I had initially thought of.

The only thing I've noticed, and this may be an unrelated bug, is that if you have the discount already in the cart and add another item, then it requires a page reload or quantity change to see the discount be applied. I tried debugging it but couldn't think of a way to fix that.

**Comment by ryanmitchell** [comment]
Spent a bit more time playing with this, and I had another thought for how to extend it a little.

It would be great to extend the coupon limitation we've started to have a minimum and maximum number of items to apply the discount to. That way you could do things like 50% off your cheapest main course by limiting it to a max of 1 item. 

All fine in theory, however, as it stands the discount would apply to all the items. Is there any way of extending getApplicableItems to say what *quantity* of each item in the cart it should apply to, as well as the item ID?

**Comment by sampoyigi** [comment]
Yea saw that coming as the `CartCondition` object doesn't know which `CartItem` it applies or applied to. 

Maybe change getApplicableItems to `isApplicableTo($cartItem)` this way some logic can be added instead of the `in_array` check?

**Comment by ryanmitchell** [comment]
Yep that sort of approach would work as it would allow the cart condition to work out if its applicable. Good solution. Want me to work on it?

**Comment by sampoyigi** [comment]
Cool, already started on the flame side, I'll finish up here so you can work on the coupons side 👍  Also good addition with the cart restriction toggle, it should replace the `self::$itemable` variable.

**Comment by sampoyigi** [comment]
I think that's done here.. Let me know if it's okay to merge!

**Comment by ryanmitchell** [comment]
I'm still seeing the issue that if a discount is on the cart already and you add another applicable item then a reload is needed to see the discount be applied. Not sure how to fix that.

I'm working on modifying the coupon side of things now.

**Comment by sampoyigi** [comment]
Addressing this https://github.com/tastyigniter/ti-ext-coupons/pull/1#discussion_r509814326 worked for me.

**Comment by ryanmitchell** [comment]
Still not working for me using the latest coupons code and flame.

Steps to recreate:
Setup a discount code with something like 50% items in one category
Add an item to your cart not in the discount code category, then apply the discount code.
Add something in the category - the 50% discount is not applied (no strikethrough on items, total incorrect)
Reapply the discount code or reload the page and it is applied
Add another item from the same category, no discount applied

**Comment by sampoyigi** [comment]
Are you pointing to the cart-item-condition branch on flame?

**Comment by ryanmitchell** [comment]
Yep, and latest coupons-limit-categories-products on cart too.

**Comment by sampoyigi** [comment]
I've put back the `applyAllConditionsToItem` call when an item is added/updated.

**Comment by ryanmitchell** [comment]
Yep that fixes it!

**Pull request merged**
