### PR TITLE
Remove lead time if it meets previous days close time

### PR DESCRIPTION
**Pull request by ryanmitchell**
Should fix: https://github.com/tastyigniter/TastyIgniter/issues/591

### CODE REVIEW

**Comment by sampoyigi** [comment]
Can you explain the changes? What if the previous close time is 2 days back? And I don't see any issue with adding the lead time to the first timeslot in a 24/7 open time... The purpose of the lead time is to give the restaurant time to prepare the order. I think it makes sense to add lead time to the open time even when they are open 24/7... or am I missing something?

**Comment by ryanmitchell** [comment]
I was checking for the close time on the previous day and if its within 1 minute of the opening time to treat it as a continuous opening and not add any lead time.

I'll leave the whether it should do it conversation to you and @breaksecurity :)

**Comment by BreakSecurity** [comment]
@sampoyigi to answer your question it makes sense like this in the 24/7 scenarios. Take a restaurant that do delivery until 1 o'clock in the night what should be the reason to add lead time at midnight if the restaurant was open? I mean if I have 40 mins lead time 23:00 23:40 00:20 and 01:00 this is correct.

If we add lead time 23:00 23:40 00:40 so we actually loose one time slot for no reason since the kitchen is already on fire

**Comment by sampoyigi** [comment]
@BreakSecurity thank you, makes sense!

@ryanmitchell I feel we might have to change the whole generate timeslot approach. Leave this one with me.

**Comment by ryanmitchell** [comment]
@sampoyigi No worries - if you need me to do anything just let me know

**Comment by sampoyigi** [comment]
@ryanmitchell any thoughts or additions on the new approach?


@BreakSecurity before I merge this please help us with a thorough test of the timeslot, lead time and pre-order hours

**Comment by BreakSecurity** [comment]
I simply overwritten workingschedule.php with the new ones and: nothing work.

IMG_20201219_111311_546

**Comment by BreakSecurity** [comment]
Ok I am testing. I noticed that differently from before if we allow preorder and put 0 days we have empty days ... instead we should have the current day

**Comment by sampoyigi** [comment]
Pushed some changes...

**Comment by BreakSecurity** [comment]
`ErrorClass 'Igniter\Flame\Location\WorkingSchedule' not found in HasWorkingHours.php line 114 at Locations_model->newWorkingSchedule('delivery', 2) in Manager.php line 243`

**Comment by sampoyigi** [comment]
Something is wrong on your end... Check the changes you applied for error/typos.

**Comment by BreakSecurity** [comment]
More or less it works...

1) Now we count only the opening days I know that it can lead to some odd scenarios. Just my opinion it adds complexity when you have to plan in advance as a restaurant owner.
immagine
immagine

Example: I have a restaurant opened only in the weekend but I want to receive orders before Wednesday  so I put 3 days of preorder. Today is Wednesday I will be able to make the preorder only for 1st sat, 1st sun, 2nd sat (of the next week). Not so convenient nor obvious. 

2) When I am close to the closure time of the restaurant I am NOT able to perform any preorder cause it says restaurant is closed.
immagine

Example: I have set 5 days for preorders (point 1 of img), it is possible to see that the current time (point 2 of img) is pretty close to closure time (point 3 of img). So in this scenario we do NOT have any valid timeslot for the current day. This lead to no allowed orders for the actual day (CORRECT) and neither for the next days (WRONG) (point 4 of img).

**PAY ATTENTION:**
If I pass the closure time it works correctly allowing me to make preorders for the next days.
immagine

@sampoyigi Tell me if every scenarios is clear enough or if you wanna some more clarifications.

**Comment by ryanmitchell** [comment]
@sampoyigi So much simpler 👍

**Comment by sampoyigi** [comment]
> Example: I have a restaurant opened only in the weekend but I want to receive orders before Wednesday so I put 3 days of preorder. Today is Wednesday I will be able to make the preorder only for 1st sat, 1st sun, 2nd sat (of the next week). Not so convenient nor obvious.

Yea using the opening hours as the timeslot range doesn't work. It fails on open till late hours too. I'll take another look at it later.

**Comment by sampoyigi** [comment]
@BreakSecurity I've made the adjustments to use the current time as the start date, let me know if this addresses the issue you raised.

**Comment by BreakSecurity** [comment]
So something is changed, but:

- Something is wrong with the pre-order setup. After having set 1 day's notice, and set as the only opening day tomorrow, the system allows me to order for tomorrow and for the following Wednesday (i.e. in 8 days)
immagine

- This, on the other hand, is what happens if the only opening day is more than one day away
immagine

- if the opening day is a little further away, it works correctly. Even though I set 3 pre-order days, being today Tuesday, it doesn't make me book for Sunday.
immagine

**Comment by BreakSecurity** [comment]
Also I still have the 2nd bug of my previous post

> 
> 
> More or less it works...
> 
>     1. Now we count only the opening days I know that it can lead to some odd scenarios. Just my opinion it adds complexity when you have to plan in advance as a restaurant owner.
>        immagine
>        immagine
> 
> 
> Example: I have a restaurant opened only in the weekend but I want to receive orders before Wednesday so I put 3 days of preorder. Today is Wednesday I will be able to make the preorder only for 1st sat, 1st sun, 2nd sat (of the next week). Not so convenient nor obvious.
> 
>     1. When I am close to the closure time of the restaurant I am NOT able to perform any preorder cause it says restaurant is closed.
>        immagine
> 
> 
> Example: I have set 5 days for preorders (point 1 of img), it is possible to see that the current time (point 2 of img) is pretty close to closure time (point 3 of img). So in this scenario we do NOT have any valid timeslot for the current day. This lead to no allowed orders for the actual day (CORRECT) and neither for the next days (WRONG) (point 4 of img).
> 
> **PAY ATTENTION:**
> If I pass the closure time it works correctly allowing me to make preorders for the next days.
> immagine
> 
> @sampoyigi Tell me if every scenarios is clear enough or if you wanna some more clarifications.

**Comment by sampoyigi** [comment]
Now both the start and end date use the current date.

To resolve the second issue, the last order time is now the same as the delivery/collection close time and lead time is now added to the ASAP order time at a later stage after the order is placed.

Related commits:
tastyigniter/TastyIgniter@dc54608ed6a87797ea262cf0bcaeec379fc19e01
tastyigniter/TastyIgniter@60d50fceaf93d374fa4b7a047ac1eb7818c036e3
tastyigniter/ti-ext-cart@071c158ecf8b1b13e16fee5971d7ff5500a3fdbf
tastyigniter/ti-ext-local@771b2fa9273133710d013ad7ac64d9a86cbd15db
tastyigniter/ti-ext-local@6e5c9293ddc49a556d728cc7d9cb88346df998ed

**Comment by BreakSecurity** [comment]
As for the days of notice, there is a small problem: the system counts exactly 24 hours from the current time, but this generates some inconveniences.
Let's take an example: today is 18:40 in the afternoon, and I have set a day as a notice
immagine
immagine
Actually I can place an order, however, by selecting all the timeslots BEFORE the current time (in this case 6:40 pm) not being able, for example, to book for dinner
immagine
Usually ordering with one day's notice is understood differently: the day before I have to be able to order for all the timeslots of the day.
In this way we have the paradoxical situation that, if I want to place an order for tomorrow at 21:00 in the evening, I will have to wait until 21:00 today to place the order!!
So to fix the situation, if current time + 24 hours falls on an opening day, it should show all timeslots of that day

**Comment by BreakSecurity** [comment]
For me is good to merge. :)

**Comment by sampoyigi** [comment]
Thank you for your time @BreakSecurity!

**Review by sampoyigi — APPROVED** [review]

**Pull request merged**
